#시큐리티 관련 설정입니다. pull하고 .yml은 .gitignore 해주세요
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kTrip
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: TUgEobrSNFtXP4INrJ7r
            client-secret: WFRCqDBZ3M
            authorization-grant-type: authorization_code
            #authorization-grant-type: client_credentials
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - email
              - name
            client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response
            # Naver 응답 값 resultCode, message, response 중 response 지정



  jwt:
    expiration_time: 86400000 #1일
    secret: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs
  #secret.key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs

logging:
  level:
    org.hibernate.sql: DEBUG